### ISSUE TITLE
use BrianFaust\Likeable\Interfaces\HasLikes;

### ISSUE THREAD

**Issue by sebastiansulinski** [faustbrian/Laravel-Likeable#18]
Documentation seem to mention this interface, but it doesn't look like it's available with the package?

**Comment by okansahin** [comment]
use this:
use BrianFaust\Likeable\Traits\HasLikesTrait;

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Likeable/commit/6e3bfced93a6dd859b23cc46b7b8e6cd20e3bdd0
