### ISSUE TITLE
Trait not found

### ISSUE THREAD

**Issue by suretarget** [faustbrian/Laravel-Likeable#4]
It seems that all version 2 of your laravel package got error with namespace. 

FatalErrorException trait not found.
**namespace BrianFaust\Likeable\Traits;**

When I removed the traits in namespace it's working fine.
**namespace BrianFaust\Likeable;**

**Comment by faustbrian** [comment]
Fixed the namespaces in the traits & instead of opening issues you could just send a PR to fix it.
